version: "3.8"
services:
  server_app:
    depends_on:
      - mysql_server
    build:
      context: ./server #Currentfile
      dockerfile: Dockerfile
    container_name: server-app
    stdin_open: true
    ports:
      #Local:Docker
      - PORT=$SERVERPORT
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_HOSTNAME=$MYSQLDB_HOSTNAME
    volumes:
      - ./server:/server-app # local path : docker path
      - ./server:/D/GHTemplates/node-js-mysql-dockercompose/server
    restart: always
    command: npm start

  mysql_server:
    image: mysql:8.0.30
    stdin_open: true
    container_name: mysql-db
    ports:
      - "3306:3306"
    command:
    - --sql_mode=
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    env_file: ./server/.env
    environment:
      - PORT=$SERVERPORT
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_HOSTNAME=$MYSQLDB_HOSTNAME
    volumes:
      - D:\MySQL_Data\GHTemplate_nodejs-mysql-dockercompose:/var/lib/mysql
    restart: unless-stopped    
